const profiles = [
  { name:'Solar-ready plateau', theme:'high solar exposure and low water demand', climate:{temperature:31,weeklyRainfall:4,dailySunHours:9.2}, terrain:{elevation:410,slope:2.2,terrain:'Flat'}, water:'Limited', soil:'Illustrative soil direction only: obtain a laboratory pH, organic carbon and NPK report before agricultural planning.', features:[['highway','State Highway access',1.2],['water','Seasonal pond',3.8],['marketplace','Local mandi',5.1]], flags:['Grid connection feasibility should be checked.','Verify land-use permissions for a solar installation.'] },
  { name:'Irrigated farm belt', theme:'water access and agricultural market links', climate:{temperature:27,weeklyRainfall:18,dailySunHours:5.2}, terrain:{elevation:285,slope:1.9,terrain:'Flat'}, water:'Good', soil:'Illustrative soil direction only: test pH, organic carbon and NPK before choosing crops.', features:[['water','Irrigation canal',0.7],['marketplace','Agricultural market',2.3],['highway','District road',1.8],['school','Village school',1.1]], flags:['Confirm irrigation allocation and seasonal water availability.','Use a certified laboratory report before selecting crops.'] },
  { name:'Logistics corridor', theme:'road connectivity and market access', climate:{temperature:29,weeklyRainfall:9,dailySunHours:5.7}, terrain:{elevation:190,slope:3.8,terrain:'Gently sloping'}, water:'Moderate', soil:'Illustrative note: perform a geotechnical investigation before logistics construction.', features:[['highway','National Highway connector',0.4],['railway','Railway station',4.1],['marketplace','Wholesale market',2.1],['hospital','District hospital',3.2]], flags:['Confirm freight access, turning radius and zoning.','A geotechnical foundation survey is recommended.'] },
  { name:'Growing residential fringe', theme:'services, access and established settlement nearby', climate:{temperature:26,weeklyRainfall:15,dailySunHours:5.8}, terrain:{elevation:145,slope:2.7,terrain:'Flat'}, water:'Moderate', soil:'Illustrative note: commission a site and groundwater assessment before construction.', features:[['highway','Urban arterial road',0.6],['school','School campus',0.8],['hospital','Community hospital',1.5],['marketplace','Neighbourhood market',1.1]], flags:['Zoning and building permissions must be confirmed.','Check drainage, water supply and traffic access.'] },
  { name:'Eco-tourism landscape', theme:'natural water features and gentle terrain', climate:{temperature:24,weeklyRainfall:27,dailySunHours:4.8}, terrain:{elevation:720,slope:7.4,terrain:'Gently sloping'}, water:'Good', soil:'Illustrative note: conduct a biodiversity and environmental sensitivity assessment.', features:[['water','Lake / reservoir edge',1.1],['highway','Scenic access road',2.7],['marketplace','Local tourism market',4.6],['school','Community school',3.8]], flags:['Environmental and tourism permissions may be needed.','Assess monsoon access and slope stability.'] },
  { name:'Industrial edge', theme:'transport access and relatively level land', climate:{temperature:30,weeklyRainfall:7,dailySunHours:4.4}, terrain:{elevation:355,slope:3.5,terrain:'Gently sloping'}, water:'Limited', soil:'Illustrative note: perform soil contamination and geotechnical testing before industrial use.', features:[['highway','Freight road',0.9],['railway','Freight rail terminal',5.3],['marketplace','Industrial market',3.6],['hospital','Emergency facility',4.4]], flags:['Check industrial zoning and environmental clearance.','Confirm utility capacity and freight movements.'] }
];
function hash(input) { let h=2166136261; for (const ch of String(input)) { h ^= ch.charCodeAt(0); h = Math.imul(h,16777619); } return h >>> 0; }
export function generateDemoContext(lat, lng, runId = '') { const index = hash(`${lat.toFixed(4)}:${lng.toFixed(4)}:${runId}`) % profiles.length; const profile = profiles[index]; const wobble = (hash(`${runId}:w`) % 15) / 10; const nearby = profile.features.map(([type,name,distance],i)=>({ type, name, distance:+Math.max(.2,distance + (i%2 ? wobble : -wobble)).toFixed(1), isDemo:true })); return { profile:profile.name, theme:profile.theme, climate:{...profile.climate,source:`Demo scenario: ${profile.name}`,confidence:'Low',isDemo:true}, terrain:{...profile.terrain,source:`Demo scenario: ${profile.name}`,confidence:'Low',isDemo:true}, water:{availability:profile.water,source:`Demo scenario: ${profile.name}`,confidence:'Low',isDemo:true}, infrastructure:{nearby,source:`Demo scenario: ${profile.name}`,confidence:'Low',isDemo:true}, soil:{source:'Government soil API unavailable — demo guidance',confidence:'Low',available:false,isDemo:true,message:profile.soil}, flags:profile.flags }; }
