import LandAnalysis from '../models/LandAnalysis.js';
import { polygonAreaHectares, centroid } from '../utils/geoCalculator.js';
import { reverseGeocode } from '../services/geocodingService.js'; import { getClimate } from '../services/climateService.js'; import { getTerrain } from '../services/gisService.js'; import { getInfrastructure } from '../services/infrastructureService.js'; import { getSoil } from '../services/soilService.js'; import { getWater } from '../services/waterService.js'; import { getFutureDevelopment } from '../services/futureDevelopmentService.js'; import { getZoning } from '../services/zoningService.js'; import { makeRecommendations } from '../services/recommendationService.js'; import { getSchemes } from '../services/schemeService.js'; import { interpret } from '../services/aiService.js'; import { generateDemoContext } from '../services/demoDataService.js';
const unavailable = (type) => ({ source: `${type} service unavailable`, confidence: 'Low', unavailable: true, type });
async function safe(fn, fallback) { try { return await fn(); } catch { return fallback; } }
export async function analyze(req,res,next) { try {
 const { geometry, currentUse='Unknown', water: inputWater='Unknown', soil: soilInput={}, radius=5, demoRunId='' } = req.body; const areaHectares = polygonAreaHectares(geometry); const [lng,lat] = centroid(geometry); const demo = generateDemoContext(lat,lng,demoRunId); const demoMode = process.env.DEMO_MODE !== 'false';
 const location = await safe(() => reverseGeocode(lat,lng), { label: `${lat.toFixed(4)}, ${lng.toFixed(4)}`, source:'Coordinates' });
 const climate = demoMode ? demo.climate : await safe(() => getClimate(lat,lng), { ...unavailable('Climate'), temperature: null, weeklyRainfall: null, dailySunHours: null });
 const terrain = demoMode ? demo.terrain : await safe(() => getTerrain(lat,lng), { ...unavailable('Terrain'), elevation: null, slope: null, terrain:'Unavailable' });
 const infrastructure = demoMode ? demo.infrastructure : await safe(() => getInfrastructure(lat,lng,radius), { source: location.road ? 'OpenStreetMap Nominatim (road at parcel centroid)' : 'OpenStreetMap infrastructure service unavailable', confidence: location.road ? 'Medium' : 'Low', unavailable: !location.road, nearby: location.road ? [{ type:'highway', name:location.road, distance:0, note:'Road returned for the parcel centroid' }] : [] });
 const soil = demoMode ? (soilInput?.ph ? await getSoil(soilInput,location) : demo.soil) : await safe(() => getSoil(soilInput, location), unavailable('Soil')); const water = inputWater !== 'Unknown' ? { availability:inputWater, source:'User-provided',confidence:'High' } : demoMode ? demo.water : await safe(() => getWater(inputWater,infrastructure), { ...unavailable('Water'), availability: inputWater });
 const [development,zoning] = await Promise.all([safe(getFutureDevelopment,unavailable('Development')), safe(getZoning,unavailable('Zoning'))]);
 const recommendations = makeRecommendations({ areaHectares, climate, terrain, infrastructure, water, zoning, currentUse }); const schemes = await getSchemes(recommendations, location); const ai = await interpret({areaHectares,location,climate,terrain,infrastructure,water,soil,zoning}, recommendations);
 const sources = [climate, terrain, infrastructure, soil, water, development, zoning]; const high = sources.filter(x=>x.confidence==='High').length; const confidence = { level: high >= 3 ? 'Medium' : 'Low', score: Math.round(sources.reduce((s,x)=>s + (x.confidence==='High'?1:x.confidence==='Medium'?.65:.3),0)/sources.length*100), sources };
 const result = { areaHectares, areaAcres:+(areaHectares*2.47105).toFixed(2), centroid:{lat,lng}, location, climate, terrain, infrastructure, soil, water, development, zoning, recommendations, schemes, ai, demo: [climate,terrain,infrastructure,soil,water].some(x=>x.isDemo) ? { active:true, profile:demo.profile, theme:demo.theme, flags:demo.flags } : {active:false}, confidence, sustainability: { score: recommendations[0].use==='Solar Farm'?86:74, note:'Model estimate based on water, terrain and land-use characteristics.' } };
 if (LandAnalysis.db.readyState === 1) await LandAnalysis.create({ data: result, recommendations, confidence }); res.json(result);
 } catch(e) { next(e); } }
